### ISSUE TITLE
Photo won't load

### ISSUE THREAD

**Issue by Fleshi1981** [craibo/ha_strava#10]
Thanks for this working fork :) The only thing that won't work is loading the photo's from Strava. Can you please take a look at that :) My programming skills aren't good enough.

**Comment by craibo** [comment]
Hi @Fleshi1981 
Yeah sure. Is it throwing any errors in the logs you can share?

**Comment by badguy99** [comment]
Might need the change on line 109-111 of this diff  at a guess - https://github.com/madmic1314/ha_strava/pull/14/files#diff-c749ece9b817fddc86a98d4b295a1744cb3de8995610dd32c34b07ed971c23ab

**Comment by craibo** [comment]
Thanks @badguy99 

@Fleshi1981 please test and let me known if the latest release resolves the issue
