### ISSUE TITLE
Strava Activity doesnt show all run activities

### ISSUE THREAD

**Issue by 1mfaasj** [craibo/ha_strava#116]
hi I don't get all the data of my strava activities back at Strava Summary when i run, should i choose a certain type like trail run?
Thanks

**Comment by craibo** [comment]
Hi @jboesh 

The Summary Stats are pulled directly from the Strava stats endpoint https://developers.strava.com/docs/reference/#api-Athletes-getStats.

It has a limitation of "Only includes data from activities set to Everyone visibilty.". We get around this by adding an extra permission  in the OAuth flow with Strava that allows pulling private activities too. If you disabled this permission when performing the OAuth it would exclude the private activities from these stats.

As I understand it any "run" type of activity should be rolled up into the all run stats

**Comment by jboesh** [comment]
so if I understand correctly you can only use the summary once you set the activities to public?  if I set individual activities to private I can retrieve it with the HA integration but not with summary
