### ISSUE TITLE
geocode.xyz - out of credits

### ISSUE THREAD

**Issue by BertrumUK** [craibo/ha_strava#117]
All my recent activities were showing as "Unknown Area" so I logged into my geocode.xyz account and found that I am out of credits -

![image](https://github.com/craibo/ha_strava/assets/22644029/a90ec1c3-3c6f-4c99-882c-b7df02aceb0d)

Not sure why this is happening as I only use Strava a couple of time a month.

**Comment by craibo** [comment]
Hi @BertrumUK 
This is due to the activites refreshing the data everytime there is an update or your HA instance is restarted.
I've added some logic in the latest releases 3.2.27+ that will use the location from the activity segment first and fallback to the geocode.xyz service if its not found.

**Comment by BertrumUK** [comment]
Thanks Tim. Working great so far.
