### ISSUE TITLE
Entities become unavailable after HA restart

### ISSUE THREAD

**Issue by stefaanbolle** [craibo/ha_strava#118]
I have the integration up and running. When setting up Strava integration, the connection is made and entities get the correct values. However, after every HA restart, all entities show unavailable. When removing the integration and reinstalling/reconfiguring it again it works again until the next HA restart. Anyone else who has experienced this and if so how to resolve? I am running the latest version of HA and the strava integration.

**Comment by kry72** [comment]
Hi, I'm having the same problem too;
entities do not become available and do not load the latest data; to solve it I have to reconfigure every time.

**Comment by craibo** [comment]
Good day,
I'm not experiencing the same issues. Are you able to share any errors from the Home Assistant logs to help triage the problem?
Thank you

**Comment by stefaanbolle** [comment]
Below lines appear in the logbook:
`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.ha_strava
Source: custom_components/ha_strava/__init__.py:854
Integration: HA Strava 2.0 (documentation, issues)
First occurred: 13 september 2023 om 11:20:16 (1 occurrences)
Last logged: 13 september 2023 om 11:20:16

Expected 1 webhook subscription for https://netmon.stefaanbolle.be/api/strava/webhook; found: 0`

and

`Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Source: custom_components/ha_strava/__init__.py:581
Integration: HA Strava 2.0 (documentation, issues)
First occurred: 13 september 2023 om 11:19:17 (1 occurrences)
Last logged: 13 september 2023 om 11:19:17

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ha_strava/__init__.py", line 732, in strava_startup_functions
    await renew_webhook_subscription(
  File "/config/custom_components/ha_strava/__init__.py", line 581, in renew_webhook_subscription
    callback_response = await websession.get(url=config_data[CONF_CALLBACK_URL])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host netmon.stefaanbolle.be:443 ssl:default [Try again]
`

**Comment by craibo** [comment]
Hi @stefaanbolle 

Could you please confirm when you configured the call back for the strava app that you used the domain `my.home-assistatnt.io` 

I would not expect to see this `Expected 1 webhook subscription for [netmon.stefaanbolle.be/api/strava/webhook](https://netmon.stefaanbolle.be/api/strava/webhook); found: 0` but rather the url `https://my.home-assistant.io/api/strava/webhook`

**Comment by stefaanbolle** [comment]
I can confirm that the caalback url ios my.home-assistatnt.io
![Screenshot 2023-09-24 at 18 57 29](https://github.com/craibo/ha_strava/assets/6658848/66d99a8f-b14d-43a3-b9cc-21bd23940c8f)

**Comment by craibo** [comment]
Closing this issue. 

I have not been able to replicate this and the errors seem to indicate that the Strava intregration is not able to reach the HA system when attempting to register the webhook call back and service start.
```
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host netmon.stefaanbolle.be:443 ssl:default [Try again
```
