### ISSUE TITLE
Strava integration failed to initiate

### ISSUE THREAD

**Issue by Crimby88** [craibo/ha_strava#129]
After the fix with summary data, it worked for a day or 2. Since then then integration fails. Tried deleting the integration and adding the files again, but the integration won't be added anymore.
I can add the client id and secret, it loads and doesn't appear. I tried both the HA-Strava-Main and HA-Strava (which is available in main/custom_components) folders.

There is no logging available.

**Comment by craibo** [comment]
Hi @Crimby88,

I haven't experienced this issue myself and I've been reloading this data alot with my testing before the latest release.
Could you please confirm you are on the latest version [3.2.28](https://github.com/craibo/ha_strava/releases/tag/3.2.28) which should be stable and contain all the fixes.

Are you adding ha_strava via the HACS integration? If you are nto seeing logs it would seem that HA is not recognising the ha_strava integration.
The component manifest, .py files and translations dir should be located here: `/config/custom_components/ha_strava`
