### ISSUE TITLE
Question about Strava Developer Program

### ISSUE THREAD

**Issue by nickdos** [craibo/ha_strava#133]
I got an email from Strava saying:

> Apply to Strava’s Developer Program
> Here’s a friendly reminder to apply to Strava’s new Developer Program by March 4th, 2024. If you don’t, you’ll lose access to our API and miss out on new program features and benefits.
> Apply Now

The linked form is quite involved and requires uploading screenshots of your application.

Does every user of this plugin need to fill out this form or risk losing access to the API?

**Comment by craibo** [comment]
Hi @nickdos 

I got the same email this morning. I've seen something about it before but ignored it as its never been worded so forcefully.

I am making the required changes based on the Brand Guidelines. Mostly around clearly indicating this is not an Official Strava app. 
The app already meets the TOS requirements.

The way the form is worded it looks like everyone will need to complete it in order to not get cut off from the APIs. 
Worst case, Strava disables the API's and will require each user to complete the form to have them re-enabled.

**Comment by craibo** [comment]
Your application has been reviewed by our team
--


<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; border-spacing: 0px !important;"><tbody><tr><td class="m_-730004407078744318hs_padded" style="margin: 0px; border-collapse: collapse; font-family: Helvetica, Arial, sans-serif; font-size: 20px; color: rgb(35, 73, 109); word-break: break-word; padding: 10px 20px;"><div id="m_-730004407078744318hs_cos_wrapper_module-1-0-2" style="color: inherit; font-size: inherit; line-height: inherit;"><div id="m_-730004407078744318hs_cos_wrapper_module-1-0-2_" style="color: inherit; font-size: inherit; line-height: inherit;"><p style="margin: 0px; color: rgb(35, 73, 109); font-family: Helvetica, Arial, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(249, 248, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; line-height: 35px;">Hi there,<br><br>We've identified your Strava API application as operating in<span> </span><em>single player mode</em><span> </span>as you only have one authenticated athlete.<br><br>That means you don't need to take any additional action to formally submit to our Developer Program if you intend to continue developing with just your own data. </p><p style="margin: 0px; color: rgb(35, 73, 109); font-family: Helvetica, Arial, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(249, 248, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; line-height: 35px;"> </p><p style="margin: 0px; color: rgb(35, 73, 109); font-family: Helvetica, Arial, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(249, 248, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; line-height: 35px;">Moving forward, here’s what you can expect for your app:</p><ul style="color: rgb(35, 73, 109); font-family: Helvetica, Arial, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(249, 248, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; line-height: 35px;"><li style="margin-left: 15px;"><strong>Overall Rate Limit:</strong><span> </span>allows for 200 requests every 15 min, with up to 2,000 requests per day</li><li style="margin-left: 15px;"><strong>Read Rate Limit:</strong><span> </span>allows for 100 requests every 15 min, with up to 1,000 requests per day</li><li style="margin-left: 15px;"><strong>Athlete Capacity:</strong><span> </span>1</li></ul><br class="Apple-interchange-newline">
