### ISSUE TITLE
YtD & Lifetime stats are wrong

### ISSUE THREAD

**Issue by VasMan** [craibo/ha_strava#143]
The Year to Date and Lifetime stats are all wrong when compared with what I see on Strava site. Any chance this can be fixed?

**Comment by craibo** [comment]
Hi @VasMan 

Could you share some examples of the issues HA vs Strava?

I haven't noticed any issues myself.

The stats for are pulled directly from Strava API response without any manipulation. 

Thanks,
Tim

**Comment by VasMan** [comment]
Hi Tim,

thanks for reaching out, please see screenshots below I just pulled from My
Strava Profile and from HA. The last ride stats I load on my HA is fine,
all data look correct. Is just the acculated ones that are wrong.

Thank you
Vasilis

From Strava Profile Page
[image: image.png]

From HA
[image: image.png]
[image: image.png]

**Comment by craibo** [comment]
Hi @VasMan 

Unfortunately those images are not showing up.

**Comment by VasMan** [comment]
Is there any update on this, or should I lose hope it will be ever fixed? 

What puzzles me most is why its only me facing this issue?

**Comment by craibo** [comment]
Hi @VasMan 

As I previously mentioned the stat numbers come directly from the Strava API. The integration does not change or calculate these, only displays them.

I have also not been able to replicate this issue with my account.

There must be something with some of your historical stats on Strava that result in them not being counted as part of the Strava API which the integration uses.

Here is the API documentation being used if you'd like to view it yourself. https://developers.strava.com/docs/reference/#api-Athletes-getStats

**Comment by VasMan** [comment]
Hi Tim,

thanks a lot for your guidance on this and confirming is not a generic
issue. I contacted Strava about this issue. Will update when I hear back,
just in case anyone else faces similar issue in the future.

BR
Vasilis

**Comment by VasMan** [comment]
Hi Tim,

I found the issue for my case. It seems that if an activity is set with
visibility to *Only You *even though all the indivindual stats of that
activity are retrieved by the API and presented by the HA integration as
individual stats activity (e.g. Strava_0_x), they dont count towards the
YtD/Lifetime data retrieved by the API. In my case I have quite a few
Strava activities set with visibility to *Only You.* On Strava there is an
option for bulk change of past activities, so if I go and set these all
with Visibility Followers, then the YtD/Lifetime data presented by the HA
integration and the underlying Strava API start aligning.

Hopefully this might help others which have similar settings.

Thank you
Vasilis
