### ISSUE TITLE
issues since upgrading to 2024.3.1

### ISSUE THREAD

**Issue by jouster1974** [craibo/ha_strava#146]
I appreciate there was an upgrade to the current build with 2024.3.0 but as I skipped this one, I have only stumbled upon this since 2024.3.1.

All previous setup entities have disappeared s when trying to re-setup the integration after using my same client ID and Client Secret (I even setup a new one of these)  

I get the following

![image](https://github.com/craibo/ha_strava/assets/15368005/2cfa9a67-b63c-4dcd-aaaf-8b37d85e3ba3)

I can confirm my remote access is set up correctly and nothing has changed there at all..

Any assistance would be appreciated... apologise if I've missed things somewhere where this was already announced as an issue

This has been bulletproof for years now so thanks for everything you've done up to this point

**Comment by jouster1974** [comment]
oddly, I've tried it again today and its managed to get through and istall itself...but now a  slightly different issues where all the data was there for about 2 minutes, well for the overall stats, and then it now all just shows unavailable for all data...so moving in the right direction but something still isn't right

**Comment by craibo** [comment]
Hi @jouster1974 

It appears that you integration is having trouble pulling and receiving updates from Strava.

The first issue would appear to be related to point 1 below.

Can I ask for some more info to help investigate?

1. If you put this url into your browser does it open you HA portal? https://my.home-assistant.io/ 
2. Is the call back url on your Strava integration setup configured to use the `https://my.home-assistant.io/` url? (as per the README)
3. If these are configured correctly can you share any logs related to the ha_strava integration? 

Thanks

**Comment by jouster1974** [comment]
thanks for the reply

I decided to remove and re-add integration one more time with a full setup and now it works exactly as expected....so no idea what the problem was but very happy its now all working as expected
