### ISSUE TITLE
Can Strava get access through Cloudflare Tunnel with a reliable IP or other authentication method?

### ISSUE THREAD

**Issue by Nelluk** [craibo/ha_strava#147]
I use Cloudflare Tunnels to securely expose my HA instance to the internet. There are various authentication methods, such as including an API key in the request, or whitelisting the IP. Has anyone gotten ha_strava to work through a system like this? I found some old threads on the Strava dev forums complaining that the IP addresses are completely unpredictable for whitelisting purposes.

**Comment by Gunsmithy** [comment]
I use a reverse proxy with mTLS certs for exposing my Home Assistant instance, so I'm also interested in other connectivity options.

Is the exposed instance strictly necessary for this integration too or is it just so Strava can push events to HA? If so, delayed polling would be sufficient for me.

**Comment by craibo** [comment]
Hi,

@Nelluk 
I'm not across Cloudflare tunnels however, as we have no control over the Strava callback source or there authentication process there is not much you can do to limit the access in that sense.
You could attempt to limit by the source domain and/or match on the request paths.

@Gunsmithy 
The same would apply as we have no control over Strava's API webhook implementation. 
Your best option is to do something similar to the above by filtering on source domain and filtering the request patchs limiting them to the required paths for strava callbacks and authentication. You would need to expose the public certs on the proxy and not on the ha instance itself.

Apologies if I've miss-understood the scenarios

**Comment by craibo** [comment]
Closing as there has been no new activity on this in a while

**Comment by milindpatel63** [comment]
> I use Cloudflare Tunnels to securely expose my HA instance to the internet. There are various authentication methods, such as including an API key in the request, or whitelisting the IP. Has anyone gotten ha_strava to work through a system like this? I found some old threads on the Strava dev forums complaining that the IP addresses are completely unpredictable for whitelisting purposes.

I created a new application in my cloudflare access for this domain "https://homeassistant.xxx.com/api/strava/webhook" and set it's policy to "Bypass" and "Everyone" in include.
So now my homeassistant domain "https://homeassistant.xxx.com" is still protected via cloudflare access and i get api access for strava without auth.
