### ISSUE TITLE
Expected str

### ISSUE THREAD

**Issue by nightmare1111** [craibo/ha_strava#149]
I get an expected str message when trying to configure the integration i am seeing the entities so the integration is working but i can't configure it for example its stuck with the default 2 activities
![Screenshot_20240402-114550_Home Assistant](https://github.com/craibo/ha_strava/assets/66319346/7eec8f28-f8a7-44f7-b828-30f767e20310)

**Comment by craibo** [comment]
Hi @nightmare1111 

I am aware of this issue and will get a fix in shortly. 
In the mean time add a single space to the optional field and this will allow you to update the config.

**Comment by craibo** [comment]
This has been fixed
