### ISSUE TITLE
Further issues with HA Strava after 2024.5.2 update (simialr to #153)

### ISSUE THREAD

**Issue by jouster1974** [craibo/ha_strava#156]
After the super quick fix to #153, it seems a similar issues is still in place after the latest core update...errors below

Logger: homeassistant.config_entries
Source: config_entries.py:575
First occurred: 02:11:45 (1 occurrences)
Last logged: 02:11:45

Error setting up entry Strava for ha_strava
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_strava/__init__.py", line 793, in async_setup_entry
    host=get_url(hass, allow_internal=False, allow_ip=False),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 212, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by craibo** [comment]
Hi @jouster1974 

I have attempted to replicate this issue but have not had any success.

I'm running the latest HA and HA Strava release versions.

The error itself appears to be a network level error or missing HA config for external url and not the integration itself.

If you are able to provide some more error info we can try debug it further.

**Comment by jouster1974** [comment]
oh that's interesting....if I wind back to the prior core build it works fine...

Basis your info, I decided to uninstall and reinstall the integration fully...and oddly when trying to add it I was informed that my instance of HASS didn't have a public URL...which is odd in itself...

Added this back in, and now everything seems to be working as expected.


Thanks for the nudge to get me to do this...I just expected that as I changed nothing it wouldn't be my side, but will make sure I at least reinstall the integration in the first instance next time
