### ISSUE TITLE
ha_strava' calls async_create_task from a thread at custom_components/ha_strava/__init__.py, line 824

### ISSUE THREAD

**Issue by haaino** [craibo/ha_strava#158]
Detected that custom integration 'ha_strava' calls async_create_task from a thread at custom_components/ha_strava/__init__.py, line 824: hass.async_create_task(async_strava_config_update_handler()), please report it to the author of the 'ha_strava' custom integration

**Comment by craibo** [comment]
Duplicates issue  [#157](https://github.com/craibo/ha_strava/issues/157)
