### ISSUE TITLE
Wrong name of activity 

### ISSUE THREAD

**Issue by maobuz** [craibo/ha_strava#17]
Real name 
![image](https://user-images.githubusercontent.com/73724063/172211233-12c6ff71-04aa-406f-8cdc-b337367fa27a.png)

integration name 

![image](https://user-images.githubusercontent.com/73724063/172211334-3e49125b-7df3-4075-9ca8-c4242b5b2fce.png)

ah.... Kcal wrong 

![image](https://user-images.githubusercontent.com/73724063/172212036-09d98d06-7b52-43e2-9a6b-673a081dfb35.png)

Home Assistant Core 2022.6.2
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

**Comment by craibo** [comment]
Hi @maobuz 
I have pushed a fix for the city name not being correctly set.

I do not get the calories in the Strava API response, it converts the kilojoules to calories using the factor `1kj = 0.239006 Cal` when calculating the calories. 
`1113kj * 0.239006 = 226 Calories`
