### ISSUE TITLE
Setup Error "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

### ISSUE THREAD

**Issue by defeatedbythecat** [craibo/ha_strava#174]
Can't get any further than this. 

I have home assistant forwarded to an external domain.

**Comment by defeatedbythecat** [comment]
Updated HA as I noticed I was a version behind and now I am getting

Config flow could not be loaded: Unknown error

**Comment by craibo** [comment]
Hi @defeatedbythecat 

Are you able to provide additional info/error logs on the issue? 
I have not been able to replicate it.

Thank you

**Comment by craibo** [comment]
No additional details. Unable to replicate with version https://github.com/craibo/ha_strava/releases/tag/3.2.40
