### ISSUE TITLE
Expose Current API Access Token

### ISSUE THREAD

**Issue by aikrana** [craibo/ha_strava#187]
Is there a way to retrieve the current API access token? Strava doesn’t allow simultaneous API access from multiple clients, and I need the token to fetch or update undocumented data available on their platform.

If not, would it be possible to expose the token somehow?

**Comment by craibo** [comment]
Hi @aikrana 

You can get the current access token from the Strava Portal. 
Login and navigate to _My Profile -> My API Application_

**Comment by aikrana** [comment]
Hi @craibo 

Yes, but the token is not programmatically accessible, and the Strava front-end is now protected by human verification systems.
