### ISSUE TITLE
Authorize error

### ISSUE THREAD

**Issue by leojcs2021** [craibo/ha_strava#21]
When opening the site to authorize, this error occurs.

{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}

**Comment by craibo** [comment]
Hi @leojcs2021 

The callback url should be using the external url configured in your home assistant system settings

Could you please confirm that:

    On your home assistant: the external url is configured correctly (This may be your nabu casa url or personal)
    On Strava: The api domain is set to `my.home-assistant.io`

You should not change the urls on your home assistant to `my.home-assistant.io`. This is only for the domain on the Strava API

**Comment by leojcs2021** [comment]
Thank you so much @craibo, it all worked out!
