### ISSUE TITLE
Installation problem - Home Assistant 2022.8.6

### ISSUE THREAD

**Issue by Thullie** [craibo/ha_strava#26]
Hi,

I'm getting this error when i want to install ha_strava

This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

**Comment by craibo** [comment]
Hi @Thullie 

The integration is configurable via the `config_flow` using the UI. 
Are you able to see an issues in your HA logs relating to the ha_strava integration?

I have checked the release notes for the 2022.8.* releases and cannot see any core breaking changes that may be causing this.

**Comment by Thullie** [comment]
you can delete this issue. 
did something wrong with copy / paste

**Comment by craibo** [comment]
Sure thing, thanks @Thullie
