### ISSUE TITLE
Future exception was never retrieved

### ISSUE THREAD

**Issue by Chreece** [craibo/ha_strava#56]
Hello Tim, 

Great update yesterday! There are massive features available now! Thank you for your hard time.

I'm having the following error in the version 3.0.10:

```
Logger: homeassistant
Source: custom_components/ha_strava/sensor.py:450
Integration: HA Strava 2.0 (documentation, issues)
First occurred: 18:12:09 (7 occurrences)
Last logged: 18:12:12

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 455, in strava_data_update_event_handler
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 579, in _async_write_ha_state
    attr = self.capability_attributes
  File "/config/custom_components/ha_strava/sensor.py", line 412, in capability_attributes
    metric = self.get_metric()
  File "/config/custom_components/ha_strava/sensor.py", line 450, in get_metric
    return sensor_metrics[self._sensor_index]
IndexError: list index out of range
```
Is there something that I can do?

**Comment by craibo** [comment]
Hi @Chreece 

I extended the activity devices to include all the useful values i could find in the API reposnes from Strava.
I haven't got to refactoring the setup of the Strava integration piece yet as you should no longer need to choose what sensors you want for an activity device. 

The quick fix for the error is: 
1. Go to the integration on HA (Settings -> Devices and Service menu)
2. Find the HA Strava 2.0 integration and select CONFIGURE
3. Immediately select SUBMIT on the popout modal. This will open the sctivity configuration
4. Select the activity type. Do NOT change the sensor dropdowns
5. Scroll to the bottom and select SUBMIT
6. Repeat the steps 2 - 5 for each of your activites you want to see. 

The service will now reload and the `IndexError: list index out of range` issue should no longer occur.

**Note:** I have noticed that the **Strava Summary** device entities sometimes get disabled after the restart. You may need to re-enable these if this occurs.
The easiest option to do this is to:
1. Select the `Entities` menu on the at the top of the `Integrations` page
2. In the hambirger menu on the right of the search bar select `Show disabled entities`
3. Search for `strava_stat`
4. Select the box to select all which will then replace the search bar with some options
5. Select `ENABLE SELECTED` 

These should become available with values in a short period of time. If not they will be there on a restart.

Apologies for the issues, I'm hoping to have this annoying bug fixed shortly.

**Comment by Chreece** [comment]
Yes, that did the trick! Thank you!
