### ISSUE TITLE
Metric or Imperial option outside of HA

### ISSUE THREAD

**Issue by BertrumUK** [craibo/ha_strava#57]
In the UK we use Celsius and Miles instead of Km's. Apart from changing HA to use the US unit system and changing all my temperatures to Fahrenheit , it would be nice if we could over-ride the metric system and have miles instead of km's. Not sure how easy this would be to implement?

I have been copying over the sensors to get miles but then every update breaks this and I need to add my hack again.

**Comment by craibo** [comment]
Hi @BertrumUK 

I had not considered that as I've only ever used Imperial OR Metric. 
There must be a correct way to handle this without you needing to change anything on HA.
I'll take a look and try get this managed so you do not need any hacks to get it to work

**Comment by craibo** [comment]
Hi @BertrumUK 

I've updated the devices in the configuration to use the [suggested unit of measure](https://developers.home-assistant.io/blog/2022/12/07/unit_system_changes?_highlight=suggested_unit_of_measurement) feature with a config option that allows selecting, default, metric or imperial for the distance sensors.
Unfortuantely, this feature need to be set on device and entity creation so it requries re-moving the integration and re-adding it with the option you want selected as part of the inital config.

Are you able to test this using the beta release 3.2.0-beta.6 or later?

If you are unable to see the beta versions in HACS follow this guide: https://hacs.xyz/docs/faq/beta/

Thank you

**Comment by BertrumUK** [comment]
Hello Tim, Let me check and report back.

**Comment by BertrumUK** [comment]
I just tried the beta but I still see my distance in KM's
![image](https://user-images.githubusercontent.com/22644029/207149317-e37003d9-2d84-4c72-add7-c283a1e12bf3.png)
![image](https://user-images.githubusercontent.com/22644029/207149451-9ee6e389-8bd4-4d29-99a0-910fa317ec1b.png)

**Comment by BertrumUK** [comment]
ah no, This was a straight update of strava after enabling the Beta version. I will do a full remove and install and update you.

**Comment by BertrumUK** [comment]
Tim,

I removed it and reiinstalled the beta multiple times and there is no change - I only get metric distance readings.

**Comment by craibo** [comment]
Hi @BertrumUK 
After fighting with HA I could not get the suggested method of implementation workign so I have reverted to doign the conversions manually. 
Let me know how you go and if it needs any changes/enhancements.
Thanks

**Comment by BertrumUK** [comment]
Morning/ Evening Tim,

Just did the update and it’s fixed it. Thank you so much for your effort in getting this working 😀
