### ISSUE TITLE
Add function to also accept private activities. and add these to the YTD distance.

### ISSUE THREAD

**Issue by alexanderevers** [craibo/ha_strava#62]
In strava there is an option to enable or disable that your private activities are also synced.

API call with read_all will give this acces.
so add this to the api call and check if the user enables or disabled this option. and add also the private activities to the YTD summary.

**Comment by craibo** [comment]
Hi @alexanderevers 
Sure, I can take a look at this. 
Do you have any Strava reference documentation urls for this?

**Comment by craibo** [comment]
This is what I've found, for the API scope change. 
There should be no change to the API calls already being made that retrun the summary stats
Will take a futher look once I have the distance unit's piece completed and working correctly.

https://developers.strava.com/docs/authentication/

**Comment by craibo** [comment]
Hi @alexanderevers 
I have changed the scope to be `activity:read_all` in the Oauth scope request.
You will need to remove and re-add the integration to update the scope when authenticating and allowing the private data to be pulled.
