### ISSUE TITLE
every 30s error in log for Strava image update

### ISSUE THREAD

**Issue by jan-gerard** [craibo/ha_strava#75]
Every 30 seconds, I get a HA_strava related error message in the log. Even when I switch off image update in the Strava config. 

```
2023-01-31 23:17:04.535 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ha_strava/camera.py", line 65, in image_update_listener
camera.rotate_img()
File "/config/custom_components/ha_strava/camera.py", line 229, in rotate_img
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 549, in async_write_ha_state
raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity strava_cam: https://dgtzuqphqg23d.cloudfront.net/xxxxxxxxxxxxxxxx.jpg>
```

Is there something I can do to fix this? And do more people have the same problem? You can open the HA logs and see if this message regularly appears.

**Comment by craibo** [comment]
Hi @jan-gerard 

I had a look at this briefly and I cannot see why the `hass` object would be null.

Are you able to confirm you have the latetest (3.2.8) version of ha_strava from the `https://github.com/craibo/ha_strava` repository?

Thank you

**Comment by jan-gerard** [comment]
> Hi @jan-gerard
> 
> I had a look at this briefly and I cannot see why the `hass` object would be null.
> 
> Are you able to confirm you have the latetest (3.2.8) version of ha_strava from the `https://github.com/craibo/ha_strava` repository?
> 
> Thank you

Yes, I run 3.2.8. And the image URL, that has attribute Hass = none, does exist.
What triggers download of Strava images so often?

**Comment by jan-gerard** [comment]
It seems like the latest update solves this. I didn't see the error since the last half hour.
