### ISSUE TITLE
a number of sensors now unavailable when upgraing to 2023.3

### ISSUE THREAD

**Issue by jouster1974** [craibo/ha_strava#79]
![image](https://user-images.githubusercontent.com/15368005/222424659-79bcabd3-e8d9-4956-858a-6561f0c8dbbd.png)

![image](https://user-images.githubusercontent.com/15368005/222424838-bf07c7b2-df5e-4967-9ade-7b7429fac000.png)

since upgrading to 2023.3...som sensors are no longer pushing data to HA.

All working fine on last version and rolling back brings them all back

**Comment by craibo** [comment]
Hi @jouster1974 
Are you seeing any errors in the logs? 
Could you please confirm the version of ha_strava you are running and that it is from the repo https://github.com/craibo/ha_strava? 
I ask as the distance icon in the images is from an older version.
I upgraded HA to 2023.3 today and I have not experienced these issues to date.

**Comment by jouster1974** [comment]
will check and revert, thanks for the quick update

**Comment by jouster1974** [comment]
turns out I had not updated for a while but have done so now and like you say, everything changed icon and details-wise...I am upgrading again now so will let you know if all good shortly...

**Comment by jouster1974** [comment]
updated to 2023.3 and all good as well..so thanks for the heads up...I'll be sure to check this first next time and loving all the new icons...

**Comment by craibo** [comment]
No problem 👍

**Comment by jouster1974** [comment]
one other thing I will mention... whilst playing with some of the new stuff.

I've noticed that the calories on my last activity...so sensor.strava_0_7 and showing wrong on the integration only...they are showing as 166kcal on the integration, but My watch and strava both show it as 599 .....so no idea what is wrong there,all other stats appear correctly.  Not the end of the world, but thought you might like to know/see

![image](https://user-images.githubusercontent.com/15368005/222453251-ea1188d7-884d-4de8-9cd9-23950e0cb57b.png)
![image](https://user-images.githubusercontent.com/15368005/222453314-77531b90-93fa-465c-8113-cb9cfae02c88.png)
