### ISSUE TITLE
Calories sensor value showing incorrectly

### ISSUE THREAD

**Issue by jouster1974** [craibo/ha_strava#80]
one other thing I will mention... whilst playing with some of the new stuff.

I've noticed that the calories on my last activity...so sensor.strava_0_7 and showing wrong on the integration only...they are showing as 166kcal on the integration, but My watch and strava both show it as 599 .....so no idea what is wrong there,all other stats appear correctly.  Not the end of the world, but thought you might like to know/see

Having had a quick look back, it seems to be a similar story on all the other captured stats for Calories only...but no idea where it is pulling that stat from as all of my runs are 10K so the count would never be that low...and even on my recent 60K ride they show as only 224... assuming it's the conversion from calories to kcals...at a multiplication factor of 4.2... it's still out by 20%

![image](https://user-images.githubusercontent.com/15368005/222453251-ea1188d7-884d-4de8-9cd9-23950e0cb57b.png)
![image](https://user-images.githubusercontent.com/15368005/222453314-77531b90-93fa-465c-8113-cb9cfae02c88.png)

_Originally posted by @jouster1974 in https://github.com/craibo/ha_strava/issues/79#issuecomment-1451937541_

**Comment by craibo** [comment]
Apologies this is not solved as I had expected.
I am using the `kilojoules` stats field and converting that to `Calories`. I do not get the calories field in the activity summary stats. I also noticed this field is only available for activity types `ride`. 
I will re-open this to look into further

**Comment by iainbullock** [comment]
I have made a change to get the Calories for all activitiy type using the Get Activity (getActivityById) method. I will post a PR

**Comment by craibo** [comment]
Thanks @iainbullock 

If we are going to pull each activity individually then it would make more sense to pull all the stats from the activity rather than the activity summary.
I'm working on an enhancement that will change this to do that and keep all the stats for an activity against the type so that the data is not mixed between the different activity types.

I'll try get this temp solution merged and released this week

**Comment by iainbullock** [comment]
Tim,

Yes I agree. I was thinking of doing something similar as a solution for
getting Stats for the week for example. I’ll await your future enhancement
and see if it does that

Thanks for your response and developing this in the first place

Iain

**Comment by craibo** [comment]
Hi @iainbullock 
I've added this to the current version as I have not had the time to spend on the refactor into seperate entities per sport type.
It's available in version 3.2.27

**Comment by iainbullock** [comment]
Thanks Tim for letting me know. I’ll check it out when I next update

Iain
