### ISSUE TITLE
would elevation gain YTD be possible

### ISSUE THREAD

**Issue by think-nice-things** [craibo/ha_strava#88]
Hi,

I like the YTD statistics as YTD ride distance.
As I ride a lot in the mountins a summary of the YTD elevation gain would be nice.
Is this possible?

**Comment by craibo** [comment]
Hi @think-nice-things 

I see this attribute is available in the Strava stats endpoint being used.
I've included the sensors for RECENT, YTD and ALL for ride and run activity types. 
These are available in version 3.2.16

**Comment by think-nice-things** [comment]
wow thanks for fast response! Looking forward to testing it.

**Comment by think-nice-things** [comment]
works great, thanks! YTD Ride Elevation Gain 19893 m ;-)
