### ISSUE TITLE
Installation issue: HA remotely accessible but can't install

### ISSUE THREAD

**Issue by bjornvaessen** [craibo/ha_strava#92]
Hi,

I followed instructions on installing the addon but I can't get past the message that my system would not be remotely accessible. As a matter of fact, I am configuring the addon remotely (from work).
Is it neccesary to have Home Assistant Cloud service (from Nabu Casa) or should "normal" remote access be sufficient?
Tried a number of restarts of the HA system but didn't help.

Best regards,

Björn

**Comment by craibo** [comment]
Hi @bjornvaessen 

Home Assistant Cloud is not required. You can use any public domain you have configured. 

What is important is :
1. Before you authenticate use the url `https://my.home-assistant.io` in the browser. When you hit that url if it doesn't know your ha instance public url it will reuqest you provide it.
2. The call back url configured in Strava is `https://my.home-assistant.io`

**Comment by bjornvaessen** [comment]
Hi Tim,

Thanks for your reply and help. Unfortunately, hitting the url https://my.home-assistant.io and setting it up correctly didn;t fix it... Still getting the message "Your Home Assistant Instance does not seem to have a public URL. The Strava Home Assistant integration requires a public URL" (after opening my HA url in the same browser tab)
Tried a re-install but also that didn't help.

**Comment by craibo** [comment]
Is your home assitant available on port 443 (https) on your public url or only the default 8123 port?
