### ISSUE TITLE
Throttled! See geocode.xyz/pricing

### ISSUE THREAD

**Issue by codyc1515** [craibo/ha_strava#94]
I am getting an error in the `sensor.strava_0_0`. It is saying `Lunch Walk | Throttled! See geocode.xyz/pricing`.

![2023-04-18 10_39_28-Overview – Home Assistant and 7 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/50791984/232625615-81b1c341-6852-481e-9554-888583958b6f.png)

**Comment by jouster1974** [comment]
also started seeing these since early in the month but not on every single activity

**Comment by craibo** [comment]
Hi @jouster1974 , @codyc1515 

It looks like the geocode.xyz the integration is using to get the address from the activity co-ordinates have changed there limits to 1 request per second on the free tier.

I'll investigate a little further but we shoudl be able to get around this by allowing a you to register on thier sit and provide the API token which will enable a higher limit. 

Alternatively I'd need to add a delay between API calls which is not a great approach.

**Comment by codyc1515** [comment]
Yes I understood that part but not sure why exactly the Strava integration is hitting their endpoints so much.

**Comment by craibo** [comment]
Hey @codyc1515 

Its not the most effecient integration tbh, as it makes a call per activity whenever there is an strava update or ha restart. This would be up to 10 calls depending on how many activites you have active.

**Comment by jouster1974** [comment]
> Hi @jouster1974 , @codyc1515
> 
> It looks like the geocode.xyz the integration is using to get the address from the activity coordinates have changed its limits to 1 request per second on the free tier.
> 
> I'll investigate a little further but we should be able to get around this by allowing you to register on their sit and provide the API token which will enable a higher limit.
> 
> Alternatively I'd need to add a delay between API calls which is not a great approach.

understood and saw similar from the link...but I'm only doing one activity a day so would be shocked if I'm hitting the limit

**Comment by craibo** [comment]
Resolved by registering for a free geocode.xyz API key and adding this to the service config from verison 3.2.17.
See README for more details
